title: n8n notes
description: Mes posts en Markdown
theme: minima

# Collection sans date dans le nom
collections:
  videos:
    output: true
    permalink: /videos/:name/

# Inclure ce qu'il faut, exclure le reste
include:
  - _videos
  - index.md
  - assets

exclude:
  - README.md
  - ongoing
  - scripts
  - node_modules
  - vendor
