title: 2nd Brain project
url: "https://nikoms.github.io"
baseurl: "/n8n"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

# Sidebar + recherche
search: true
lunr:
  search_within_pages: true

# Ta collection sans date dans le nom des fichiers
collections:
  videos:
    output: true
    permalink: /videos/:name/

# Appliquer layout + sidebar par défaut aux items de _videos
defaults:
  - scope: { path: "", type: videos }
    values:
      layout: single
      sidebar:
        nav: "videos_nav"

include:
  - _videos
  - index.md
  - videos.md

# Nettoyage
exclude:
  - ongoing
  - README.md
