title: 2nd Brain project
url: "https://nikoms.github.io"
baseurl: "/n8n"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Configure the feed
feed:
  collections:
    - videos
    - books
  excerpt_only: true

# Sidebar + recherche
search: true
lunr:
  search_within_pages: true

# Ta collection sans date dans le nom des fichiers
collections:
  videos:
    output: true
    permalink: /videos/:name/
  books:
    output: true
    permalink: /books/:name/

include:
  - _videos
  - videos.md
  - index.md
  - _books
  - books.md

# Nettoyage
exclude:
  - ongoing
  - README.md
